In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[5]

5

In [6]:
arr[5:8]

array([5, 6, 7])

In [7]:
arr[:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [16]:
arr= np.arange(0,11)

In [17]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
arr[0:5] = 100

In [21]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [22]:
arr = np.arange(0,11)

In [23]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
slice_of_arr = arr[0:5]

In [26]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [27]:
slice_of_arr[:] = 99

In [28]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [29]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [30]:
arr_copy = arr.copy()

In [31]:
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [32]:
arr_copy[:] = 100

In [33]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [34]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [35]:
array = [5,10,15],[20,25,20],[35,40,35]

In [36]:
array

([5, 10, 15], [20, 25, 20], [35, 40, 35])

In [39]:
arr_2d = np.array(array)

In [40]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 20],
       [35, 40, 35]])

In [42]:
arr_2d.shape

(3, 3)

In [43]:
arr_2d[1][1]

25

In [44]:
arr_2d[1,1]

25

In [45]:
arr_2d[0][2]

15

In [46]:
arr_2d[0,2]

15

In [61]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [60]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [51]:
arr_2d[2]

array([35, 40, 35])

In [62]:
arr = np.arange(1,11)

In [63]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
bool_arr = arr >4

In [66]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [67]:
arr = np.arange(0,10)

In [68]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [70]:
arr - 2


array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [71]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [72]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [73]:
arr- arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [74]:
1 / arr

/tmp/ipykernel_207032/1528351372.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [75]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])